package hayride-dev:platform@0.0.1;

world platform {
    
    import wasi:http/types@0.2.0;
    import wasi:http/outgoing-handler@0.2.0;

    /// HTTP proxies have access to time and randomness.
    import wasi:clocks/wall-clock@0.2.0;
    import wasi:clocks/monotonic-clock@0.2.0;
    import wasi:random/random@0.2.0;

    /// Proxies have standard output and error streams which are expected to
    /// terminate in a developer-facing console provided by the host.
    import wasi:cli/stdout@0.2.0;
    import wasi:cli/stderr@0.2.0;
    import wasi:cli/environment@0.2.0;
    import wasi:filesystem/types@0.2.0;
    import wasi:filesystem/preopens@0.2.0;
    /// TODO: this is a temporary workaround until component tooling is able to
    /// gracefully handle the absence of stdin. Hosts must return an eof stream
    /// for this import, which is what wasi-libc + tooling will do automatically
    /// when this import is properly removed.
    import wasi:cli/stdin@0.2.0;
 
    export wasi:cli/run@0.2.0; 
}

